### ISSUE TITLE
Epoll bug 问题

### ISSUE THREAD

**Issue by wangzzu** [wangzzu/awesome#12]
Java NIO有著名的 epoll bug

- 现象：导致 Selector 空轮询，最终导致 CPU 100%，JDK1.7依然没有解决这个问题，只是降低了这个问题发生概率；
- 目的
 1. 研究 Kafka 是如何解决这个问题；
 2. 研究 Netty 是如何解决这个问题；
- 输出：一篇Wiki，也可以组内做一个分享。

**Comment by generalthink** [comment]
你好,关于研究 Kafka 是如何解决epoll空转问题,请问你知道了吗?

**Comment by wangzzu** [comment]
@generalthink 这个一直荒废了，没有去查，汗颜
