### ISSUE TITLE
《Computer System》学习

### ISSUE THREAD

**Issue by wangzzu** [wangzzu/awesome#13]
计划每半年左右定一个专题去学习，借鉴于这篇文章[技术大牛养成指南，一篇不鸡汤的成功学实践](https://mp.weixin.qq.com/s/5PfaaWBFCw5-MuAnR7ABiQ)的方法论，从今年的9.11到12.31准备去学习操作系统这个方向的内容，这也是自己年初给自己定的计划。

- 参考书：[深入理解计算机系统](https://item.jd.com/12006637.html)、[操作系统：精髓与设计原理](https://item.jd.com/10255221.html)、[深入理解LINUX内核](https://item.jd.com/10100237.html)；
- 参考视频教程：CMU 的 [CSAPP](http://csapp.cs.cmu.edu/3e/students.html)。
- 计划按主题输出相应的博客，每周看一节教程的视频。

**Comment by Stephan14** [comment]
请问输出博客有连接吗？学习一下

**Comment by wangzzu** [comment]
@Stephan14 尴尬，还没开始，最近一年再搞其他的事情，还是想想怎么提高自己的效率
