### ISSUE TITLE
餐馆米其林排名

### ISSUE THREAD

**Issue by wangzzu** [wangzzu/awesome#2]
# 想法来源
个人一直比较喜欢听《晓松奇谈》，有几期讲到日本料理，中间提到过日本一些入选米其林的料理店，但在网上搜了一下发现大陆入选米其林的餐馆少之又少，而且目前只有上海加入米其林评选。

每当到一个地方去玩时，吃货们都会让当地人去推荐一些本地餐馆，或者在美团和点评上去找一些评价较好的餐馆，但是美团、点评上的餐馆即使按好评优先得到的排名依然不尽如人意。

因此，我就想写一个小程序，首先抓去美团点评上的评论数据，根据一个模型来得到这个餐馆的分数，根据分数获取一些餐馆米其林排名。

# 技术准备

- 爬虫
- 机器学习算法

**Comment by qiudeyang** [comment]
机器学习算法，师兄还会这个。

**Comment by wangzzu** [comment]
@qiudeyang 定的一些计划，通过一个小项目去学习，这样才能效率才会更高一些。

**Comment by wangzzu** [comment]
我已放弃😂
