### ISSUE TITLE
《linux-monitoring》这本小书的学习

### ISSUE THREAD

**Issue by wangzzu** [wangzzu/awesome#6]
- 原因：自己对很多的 linux 命令并不是很熟悉，想在空余时间去学习一些这些命令，以后在用到时就会更得心应手些。
- 内容：学习 linux 的命令，在 [坚持学习 Linux 命令](https://www.gitbook.com/book/wangzzu/-linux/details) 这本电子书上更新；
- 时间：每周总结三条。

**Comment by wangzzu** [comment]
### 170417-170423
计划：top、ps、grep三条命令。

**Comment by wangzzu** [comment]
总结的命令，更新在这篇文章上，主要是系统方面的命令：[Linux 常用的一些系统命令](http://matt33.com/2017/07/16/linux-system-cmd/)

**Comment by wangzzu** [comment]
学习《linux-monitoring》这本书的内容，这本书只有40页左右

- 输出1、2篇博客；
- 完成时间：2017.10.22.

**Comment by Stephan14** [comment]
请问有相关的pdf吗？在网上没有找到此书

**Comment by wangzzu** [comment]
这个先关闭了，不过后面确实打算输出一些系统或硬件相关的总结思考
